webtalk_init -webtalk_dir D:\\WORKSPACE\\FPGA\\Final_Project_RTES\\Final_Project_RTES.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-11-07 14:26:52" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "q9lobm7skurfdh8nlngh2itl4i" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.4_43" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "43" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2095 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1541575248422" -context "sdk\\\\bsp/1541575248422"
webtalk_add_data -client sdk -key hwid -value "1541562060649" -context "sdk\\\\bsp/1541575248422"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1541575248422"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1541575248422"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1541575248422"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1541575612291"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1541575612291"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1541575612291"
webtalk_add_data -client sdk -key DebugCount -value "3" -context "sdk\\\\bsp/1541575612291"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1541575612291"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1541575612291"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1541575612291"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1541575612291"
webtalk_transmit -clientid 495025606 -regid "" -xml D:\\WORKSPACE\\FPGA\\Final_Project_RTES\\Final_Project_RTES.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\WORKSPACE\\FPGA\\Final_Project_RTES\\Final_Project_RTES.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\WORKSPACE\\FPGA\\Final_Project_RTES\\Final_Project_RTES.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
